### ISSUE TITLE
incorrect cc_toolchain with bzlmod and Linux aarm64?

### ISSUE THREAD

**Issue by kolloch** [buildbuddy-io/buildbuddy-toolchain#34] opened 2024-12-03 15:38 UTC
I want to use the buildbuddy toolchains only in CI for now.

I have this in my MODULE.bazel:

```starlark
bazel_dep(name = "toolchains_buildbuddy")
git_override(
    module_name = "toolchains_buildbuddy",
    commit = "eb143d1cf81dcc3ddbf0be5b9950cf8c14aa2de9",
    remote = "git@github.com:buildbuddy-io/buildbuddy-toolchain.git",
)
buildbuddy = use_extension("@toolchains_buildbuddy//:extensions.bzl", "buildbuddy")
buildbuddy.platform(buildbuddy_container_image = "UBUNTU22_04_IMAGE")
use_repo(buildbuddy, "buildbuddy_toolchain")
```

And then in an included bazelrc file (the remote config is NOT enabled locally, only in CI):

```text
# Toolchain
common:remote --extra_execution_platforms=@buildbuddy_toolchain//:platform_linux_x86_64
common:remote --host_platform=@buildbuddy_toolchain//:platform_linux_x86_64
common:remote --platforms=@buildbuddy_toolchain//:platform_linux_x86_64
common:remote --crosstool_top=@buildbuddy_toolchain//:platform_linux_x86_64
common:remote --extra_toolchains=@buildbuddy_toolchain//:cc_toolchain

# ... and further recommended options
```

When I comment out the MODULE.bazel lines, then this build works nicely in my Bazel workspace (it is a simple rust crate as you suspect):

```sh
bazel build //crates/hello_world --toolchain_resolution_debug='@@bazel_tools//tools/cpp:toolchain_type'
```

If I uncomment the lines above, I get the following error in Linux AARM64 (a VM on Mac OS):

```sh
INFO: ToolchainResolution: Performing resolution of @@bazel_tools//tools/cpp:toolchain_type for target platform @@platforms//host:host
      ToolchainResolution:   Rejected toolchain @@toolchains_buildbuddy~~buildbuddy~buildbuddy_toolchain//:ubuntu_local_cc_toolchain; mismatching values: x86_64
      ToolchainResolution:   Rejected toolchain @@toolchains_buildbuddy~~buildbuddy~buildbuddy_toolchain//:ubuntu_local_cc_toolchain; mismatching values: x86_64
      ToolchainResolution:   Rejected toolchain @@toolchains_buildbuddy~~buildbuddy~buildbuddy_toolchain//:msvc_toolchain; mismatching values: x86_64, windows
      ToolchainResolution:   Toolchain @@bazel_tools~cc_configure_extension~local_config_cc//:cc-compiler-aarch64 is compatible with target plaform, searching for execution platforms:
      ToolchainResolution:     Incompatible execution platform @@toolchains_buildbuddy~~buildbuddy~buildbuddy_toolchain//:platform_darwin_arm64; mismatching values: linux
      ToolchainResolution:     Incompatible execution platform @@toolchains_buildbuddy~~buildbuddy~buildbuddy_toolchain//:platform_darwin; mismatching values: aarch64, linux
      ToolchainResolution:     Compatible execution platform @@toolchains_buildbuddy~~buildbuddy~buildbuddy_toolchain//:platform_linux_arm64
      ToolchainResolution:     Incompatible execution platform @@toolchains_buildbuddy~~buildbuddy~buildbuddy_toolchain//:platform_linux_x86_64; mismatching values: aarch64
      ToolchainResolution:     Incompatible execution platform @@toolchains_buildbuddy~~buildbuddy~buildbuddy_toolchain//:platform_windows; mismatching values: aarch64, linux
      ToolchainResolution:     Compatible execution platform @@platforms//host:host
      ToolchainResolution:   Rejected toolchain @@bazel_tools~cc_configure_extension~local_config_cc//:cc-compiler-armeabi-v7a; mismatching values: armv7, android
      ToolchainResolution:   Toolchain @@rules_cc~~cc_configure_extension~local_config_cc//:cc-compiler-aarch64 is compatible with target plaform, searching for execution platforms:
      ToolchainResolution:     Incompatible execution platform @@toolchains_buildbuddy~~buildbuddy~buildbuddy_toolchain//:platform_darwin_arm64; mismatching values: linux
      ToolchainResolution:     Incompatible execution platform @@toolchains_buildbuddy~~buildbuddy~buildbuddy_toolchain//:platform_darwin; mismatching values: aarch64, linux
      ToolchainResolution:     Skipping execution platform @@toolchains_buildbuddy~~buildbuddy~buildbuddy_toolchain//:platform_linux_arm64; it has already selected a toolchain
      ToolchainResolution:     Incompatible execution platform @@toolchains_buildbuddy~~buildbuddy~buildbuddy_toolchain//:platform_linux_x86_64; mismatching values: aarch64
      ToolchainResolution:     Incompatible execution platform @@toolchains_buildbuddy~~buildbuddy~buildbuddy_toolchain//:platform_windows; mismatching values: aarch64, linux
      ToolchainResolution:     Skipping execution platform @@platforms//host:host; it has already selected a toolchain
      ToolchainResolution:   Rejected toolchain @@rules_cc~~cc_configure_extension~local_config_cc//:cc-compiler-armeabi-v7a; mismatching values: armv7, android
      ToolchainResolution:   Toolchain @@local_config_cc//:cc-compiler-aarch64 is compatible with target plaform, searching for execution platforms:
      ToolchainResolution:     Incompatible execution platform @@toolchains_buildbuddy~~buildbuddy~buildbuddy_toolchain//:platform_darwin_arm64; mismatching values: linux
      ToolchainResolution:     Incompatible execution platform @@toolchains_buildbuddy~~buildbuddy~buildbuddy_toolchain//:platform_darwin; mismatching values: aarch64, linux
      ToolchainResolution:     Skipping execution platform @@toolchains_buildbuddy~~buildbuddy~buildbuddy_toolchain//:platform_linux_arm64; it has already selected a toolchain
      ToolchainResolution:     Incompatible execution platform @@toolchains_buildbuddy~~buildbuddy~buildbuddy_toolchain//:platform_linux_x86_64; mismatching values: aarch64
      ToolchainResolution:     Incompatible execution platform @@toolchains_buildbuddy~~buildbuddy~buildbuddy_toolchain//:platform_windows; mismatching values: aarch64, linux
      ToolchainResolution:     Skipping execution platform @@platforms//host:host; it has already selected a toolchain
      ToolchainResolution:   Rejected toolchain @@local_config_cc//:cc-compiler-armeabi-v7a; mismatching values: armv7, android
      ToolchainResolution: Recap of selected @@bazel_tools//tools/cpp:toolchain_type toolchains for target platform @@platforms//host:host:
      ToolchainResolution:   Selected @@bazel_tools~cc_configure_extension~local_config_cc//:cc-compiler-aarch64 to run on execution platform @@toolchains_buildbuddy~~buildbuddy~buildbuddy_toolchain//:platform_linux_arm64
      ToolchainResolution:   Selected @@bazel_tools~cc_configure_extension~local_config_cc//:cc-compiler-aarch64 to run on execution platform @@platforms//host:host
INFO: ToolchainResolution: Target platform @@platforms//host:host: Selected execution platform @@toolchains_buildbuddy~~buildbuddy~buildbuddy_toolchain//:platform_linux_arm64, type @@rules_rust~//rust:toolchain_type -> toolchain @@rules_rust~~rust~rust_linux_aarch64__aarch64-unknown-linux-gnu__stable_tools//:rust_toolchain, type @@bazel_tools//tools/cpp:toolchain_type -> toolchain @@bazel_tools~cc_configure_extension~local_config_cc//:cc-compiler-aarch64
INFO: ToolchainResolution: Performing resolution of @@bazel_tools//tools/cpp:toolchain_type for target platform @@platforms//host:host
      ToolchainResolution:   Rejected toolchain @@toolchains_buildbuddy~~buildbuddy~buildbuddy_toolchain//:ubuntu_local_cc_toolchain; mismatching values: x86_64
      ToolchainResolution:   Rejected toolchain @@toolchains_buildbuddy~~buildbuddy~buildbuddy_toolchain//:ubuntu_local_cc_toolchain; mismatching values: x86_64
      ToolchainResolution:   Rejected toolchain @@toolchains_buildbuddy~~buildbuddy~buildbuddy_toolchain//:msvc_toolchain; mismatching values: x86_64, windows
      ToolchainResolution:   Toolchain @@bazel_tools~cc_configure_extension~local_config_cc//:cc-compiler-aarch64 is compatible with target plaform, searching for execution platforms:
      ToolchainResolution:     Incompatible execution platform @@toolchains_buildbuddy~~buildbuddy~buildbuddy_toolchain//:platform_darwin_arm64; mismatching values: linux
      ToolchainResolution:     Incompatible execution platform @@toolchains_buildbuddy~~buildbuddy~buildbuddy_toolchain//:platform_darwin; mismatching values: aarch64, linux
      ToolchainResolution:     Compatible execution platform @@toolchains_buildbuddy~~buildbuddy~buildbuddy_toolchain//:platform_linux_arm64
      ToolchainResolution:     Incompatible execution platform @@toolchains_buildbuddy~~buildbuddy~buildbuddy_toolchain//:platform_linux_x86_64; mismatching values: aarch64
      ToolchainResolution:     Incompatible execution platform @@toolchains_buildbuddy~~buildbuddy~buildbuddy_toolchain//:platform_windows; mismatching values: aarch64, linux
      ToolchainResolution:     Compatible execution platform @@platforms//host:host
      ToolchainResolution:   Rejected toolchain @@bazel_tools~cc_configure_extension~local_config_cc//:cc-compiler-armeabi-v7a; mismatching values: armv7, android
      ToolchainResolution:   Toolchain @@rules_cc~~cc_configure_extension~local_config_cc//:cc-compiler-aarch64 is compatible with target plaform, searching for execution platforms:
      ToolchainResolution:     Incompatible execution platform @@toolchains_buildbuddy~~buildbuddy~buildbuddy_toolchain//:platform_darwin_arm64; mismatching values: linux
      ToolchainResolution:     Incompatible execution platform @@toolchains_buildbuddy~~buildbuddy~buildbuddy_toolchain//:platform_darwin; mismatching values: aarch64, linux
      ToolchainResolution:     Skipping execution platform @@toolchains_buildbuddy~~buildbuddy~buildbuddy_toolchain//:platform_linux_arm64; it has already selected a toolchain
      ToolchainResolution:     Incompatible execution platform @@toolchains_buildbuddy~~buildbuddy~buildbuddy_toolchain//:platform_linux_x86_64; mismatching values: aarch64
      ToolchainResolution:     Incompatible execution platform @@toolchains_buildbuddy~~buildbuddy~buildbuddy_toolchain//:platform_windows; mismatching values: aarch64, linux
      ToolchainResolution:     Skipping execution platform @@platforms//host:host; it has already selected a toolchain
      ToolchainResolution:   Rejected toolchain @@rules_cc~~cc_configure_extension~local_config_cc//:cc-compiler-armeabi-v7a; mismatching values: armv7, android
      ToolchainResolution:   Toolchain @@local_config_cc//:cc-compiler-aarch64 is compatible with target plaform, searching for execution platforms:
      ToolchainResolution:     Incompatible execution platform @@toolchains_buildbuddy~~buildbuddy~buildbuddy_toolchain//:platform_darwin_arm64; mismatching values: linux
      ToolchainResolution:     Incompatible execution platform @@toolchains_buildbuddy~~buildbuddy~buildbuddy_toolchain//:platform_darwin; mismatching values: aarch64, linux
      ToolchainResolution:     Skipping execution platform @@toolchains_buildbuddy~~buildbuddy~buildbuddy_toolchain//:platform_linux_arm64; it has already selected a toolchain
      ToolchainResolution:     Incompatible execution platform @@toolchains_buildbuddy~~buildbuddy~buildbuddy_toolchain//:platform_linux_x86_64; mismatching values: aarch64
      ToolchainResolution:     Incompatible execution platform @@toolchains_buildbuddy~~buildbuddy~buildbuddy_toolchain//:platform_windows; mismatching values: aarch64, linux
      ToolchainResolution:     Skipping execution platform @@platforms//host:host; it has already selected a toolchain
      ToolchainResolution:   Rejected toolchain @@local_config_cc//:cc-compiler-armeabi-v7a; mismatching values: armv7, android
      ToolchainResolution: Recap of selected @@bazel_tools//tools/cpp:toolchain_type toolchains for target platform @@platforms//host:host:
      ToolchainResolution:   Selected @@bazel_tools~cc_configure_extension~local_config_cc//:cc-compiler-aarch64 to run on execution platform @@toolchains_buildbuddy~~buildbuddy~buildbuddy_toolchain//:platform_linux_arm64
      ToolchainResolution:   Selected @@bazel_tools~cc_configure_extension~local_config_cc//:cc-compiler-aarch64 to run on execution platform @@platforms//host:host
INFO: ToolchainResolution: Target platform @@platforms//host:host: Selected execution platform @@toolchains_buildbuddy~~buildbuddy~buildbuddy_toolchain//:platform_linux_arm64, type @@bazel_tools//tools/cpp:toolchain_type -> toolchain @@bazel_tools~cc_configure_extension~local_config_cc//:cc-compiler-aarch64
INFO: ToolchainResolution: Target platform @@platforms//host:host: Selected execution platform @@toolchains_buildbuddy~~buildbuddy~buildbuddy_toolchain//:platform_linux_arm64, type @@bazel_tools//tools/cpp:toolchain_type -> toolchain @@bazel_tools~cc_configure_extension~local_config_cc//:cc-compiler-aarch64
INFO: ToolchainResolution: Performing resolution of @@bazel_tools//tools/cpp:toolchain_type for target platform @@toolchains_buildbuddy~~buildbuddy~buildbuddy_toolchain//:platform_linux_arm64
      ToolchainResolution:   Rejected toolchain @@toolchains_buildbuddy~~buildbuddy~buildbuddy_toolchain//:ubuntu_local_cc_toolchain; mismatching values: x86_64
      ToolchainResolution:   Rejected toolchain @@toolchains_buildbuddy~~buildbuddy~buildbuddy_toolchain//:ubuntu_local_cc_toolchain; mismatching values: x86_64
      ToolchainResolution:   Rejected toolchain @@toolchains_buildbuddy~~buildbuddy~buildbuddy_toolchain//:msvc_toolchain; mismatching values: x86_64, windows
      ToolchainResolution:   Toolchain @@bazel_tools~cc_configure_extension~local_config_cc//:cc-compiler-aarch64 is compatible with target plaform, searching for execution platforms:
      ToolchainResolution:     Incompatible execution platform @@toolchains_buildbuddy~~buildbuddy~buildbuddy_toolchain//:platform_darwin_arm64; mismatching values: linux
      ToolchainResolution:     Incompatible execution platform @@toolchains_buildbuddy~~buildbuddy~buildbuddy_toolchain//:platform_darwin; mismatching values: aarch64, linux
      ToolchainResolution:     Compatible execution platform @@toolchains_buildbuddy~~buildbuddy~buildbuddy_toolchain//:platform_linux_arm64
      ToolchainResolution:     Incompatible execution platform @@toolchains_buildbuddy~~buildbuddy~buildbuddy_toolchain//:platform_linux_x86_64; mismatching values: aarch64
      ToolchainResolution:     Incompatible execution platform @@toolchains_buildbuddy~~buildbuddy~buildbuddy_toolchain//:platform_windows; mismatching values: aarch64, linux
      ToolchainResolution:     Compatible execution platform @@platforms//host:host
      ToolchainResolution:   Rejected toolchain @@bazel_tools~cc_configure_extension~local_config_cc//:cc-compiler-armeabi-v7a; mismatching values: armv7, android
      ToolchainResolution:   Toolchain @@rules_cc~~cc_configure_extension~local_config_cc//:cc-compiler-aarch64 is compatible with target plaform, searching for execution platforms:
      ToolchainResolution:     Incompatible execution platform @@toolchains_buildbuddy~~buildbuddy~buildbuddy_toolchain//:platform_darwin_arm64; mismatching values: linux
      ToolchainResolution:     Incompatible execution platform @@toolchains_buildbuddy~~buildbuddy~buildbuddy_toolchain//:platform_darwin; mismatching values: aarch64, linux
      ToolchainResolution:     Skipping execution platform @@toolchains_buildbuddy~~buildbuddy~buildbuddy_toolchain//:platform_linux_arm64; it has already selected a toolchain
      ToolchainResolution:     Incompatible execution platform @@toolchains_buildbuddy~~buildbuddy~buildbuddy_toolchain//:platform_linux_x86_64; mismatching values: aarch64
      ToolchainResolution:     Incompatible execution platform @@toolchains_buildbuddy~~buildbuddy~buildbuddy_toolchain//:platform_windows; mismatching values: aarch64, linux
      ToolchainResolution:     Skipping execution platform @@platforms//host:host; it has already selected a toolchain
      ToolchainResolution:   Rejected toolchain @@rules_cc~~cc_configure_extension~local_config_cc//:cc-compiler-armeabi-v7a; mismatching values: armv7, android
      ToolchainResolution:   Toolchain @@local_config_cc//:cc-compiler-aarch64 is compatible with target plaform, searching for execution platforms:
      ToolchainResolution:     Incompatible execution platform @@toolchains_buildbuddy~~buildbuddy~buildbuddy_toolchain//:platform_darwin_arm64; mismatching values: linux
      ToolchainResolution:     Incompatible execution platform @@toolchains_buildbuddy~~buildbuddy~buildbuddy_toolchain//:platform_darwin; mismatching values: aarch64, linux
      ToolchainResolution:     Skipping execution platform @@toolchains_buildbuddy~~buildbuddy~buildbuddy_toolchain//:platform_linux_arm64; it has already selected a toolchain
      ToolchainResolution:     Incompatible execution platform @@toolchains_buildbuddy~~buildbuddy~buildbuddy_toolchain//:platform_linux_x86_64; mismatching values: aarch64
      ToolchainResolution:     Incompatible execution platform @@toolchains_buildbuddy~~buildbuddy~buildbuddy_toolchain//:platform_windows; mismatching values: aarch64, linux
      ToolchainResolution:     Skipping execution platform @@platforms//host:host; it has already selected a toolchain
      ToolchainResolution:   Rejected toolchain @@local_config_cc//:cc-compiler-armeabi-v7a; mismatching values: armv7, android
      ToolchainResolution: Recap of selected @@bazel_tools//tools/cpp:toolchain_type toolchains for target platform @@toolchains_buildbuddy~~buildbuddy~buildbuddy_toolchain//:platform_linux_arm64:
      ToolchainResolution:   Selected @@bazel_tools~cc_configure_extension~local_config_cc//:cc-compiler-aarch64 to run on execution platform @@toolchains_buildbuddy~~buildbuddy~buildbuddy_toolchain//:platform_linux_arm64
      ToolchainResolution:   Selected @@bazel_tools~cc_configure_extension~local_config_cc//:cc-compiler-aarch64 to run on execution platform @@platforms//host:host
INFO: ToolchainResolution: Target platform @@toolchains_buildbuddy~~buildbuddy~buildbuddy_toolchain//:platform_linux_arm64: Selected execution platform @@toolchains_buildbuddy~~buildbuddy~buildbuddy_toolchain//:platform_linux_arm64, type @@rules_rust~//rust:toolchain_type -> toolchain @@rules_rust~~rust~rust_linux_aarch64__aarch64-unknown-linux-gnu__stable_tools//:rust_toolchain, type @@bazel_tools//tools/cpp:toolchain_type -> toolchain @@bazel_tools~cc_configure_extension~local_config_cc//:cc-compiler-aarch64
INFO: ToolchainResolution: Performing resolution of @@bazel_tools//tools/cpp:toolchain_type for target platform @@toolchains_buildbuddy~~buildbuddy~buildbuddy_toolchain//:platform_linux_arm64
      ToolchainResolution:   Rejected toolchain @@toolchains_buildbuddy~~buildbuddy~buildbuddy_toolchain//:ubuntu_local_cc_toolchain; mismatching values: x86_64
      ToolchainResolution:   Rejected toolchain @@toolchains_buildbuddy~~buildbuddy~buildbuddy_toolchain//:ubuntu_local_cc_toolchain; mismatching values: x86_64
      ToolchainResolution:   Rejected toolchain @@toolchains_buildbuddy~~buildbuddy~buildbuddy_toolchain//:msvc_toolchain; mismatching values: x86_64, windows
      ToolchainResolution:   Toolchain @@bazel_tools~cc_configure_extension~local_config_cc//:cc-compiler-aarch64 is compatible with target plaform, searching for execution platforms:
      ToolchainResolution:     Incompatible execution platform @@toolchains_buildbuddy~~buildbuddy~buildbuddy_toolchain//:platform_darwin_arm64; mismatching values: linux
      ToolchainResolution:     Incompatible execution platform @@toolchains_buildbuddy~~buildbuddy~buildbuddy_toolchain//:platform_darwin; mismatching values: aarch64, linux
      ToolchainResolution:     Compatible execution platform @@toolchains_buildbuddy~~buildbuddy~buildbuddy_toolchain//:platform_linux_arm64
      ToolchainResolution:     Incompatible execution platform @@toolchains_buildbuddy~~buildbuddy~buildbuddy_toolchain//:platform_linux_x86_64; mismatching values: aarch64
      ToolchainResolution:     Incompatible execution platform @@toolchains_buildbuddy~~buildbuddy~buildbuddy_toolchain//:platform_windows; mismatching values: aarch64, linux
      ToolchainResolution:     Compatible execution platform @@platforms//host:host
      ToolchainResolution:   Rejected toolchain @@bazel_tools~cc_configure_extension~local_config_cc//:cc-compiler-armeabi-v7a; mismatching values: armv7, android
      ToolchainResolution:   Toolchain @@rules_cc~~cc_configure_extension~local_config_cc//:cc-compiler-aarch64 is compatible with target plaform, searching for execution platforms:
      ToolchainResolution:     Incompatible execution platform @@toolchains_buildbuddy~~buildbuddy~buildbuddy_toolchain//:platform_darwin_arm64; mismatching values: linux
      ToolchainResolution:     Incompatible execution platform @@toolchains_buildbuddy~~buildbuddy~buildbuddy_toolchain//:platform_darwin; mismatching values: aarch64, linux
      ToolchainResolution:     Skipping execution platform @@toolchains_buildbuddy~~buildbuddy~buildbuddy_toolchain//:platform_linux_arm64; it has already selected a toolchain
      ToolchainResolution:     Incompatible execution platform @@toolchains_buildbuddy~~buildbuddy~buildbuddy_toolchain//:platform_linux_x86_64; mismatching values: aarch64
      ToolchainResolution:     Incompatible execution platform @@toolchains_buildbuddy~~buildbuddy~buildbuddy_toolchain//:platform_windows; mismatching values: aarch64, linux
      ToolchainResolution:     Skipping execution platform @@platforms//host:host; it has already selected a toolchain
      ToolchainResolution:   Rejected toolchain @@rules_cc~~cc_configure_extension~local_config_cc//:cc-compiler-armeabi-v7a; mismatching values: armv7, android
      ToolchainResolution:   Toolchain @@local_config_cc//:cc-compiler-aarch64 is compatible with target plaform, searching for execution platforms:
      ToolchainResolution:     Incompatible execution platform @@toolchains_buildbuddy~~buildbuddy~buildbuddy_toolchain//:platform_darwin_arm64; mismatching values: linux
      ToolchainResolution:     Incompatible execution platform @@toolchains_buildbuddy~~buildbuddy~buildbuddy_toolchain//:platform_darwin; mismatching values: aarch64, linux
      ToolchainResolution:     Skipping execution platform @@toolchains_buildbuddy~~buildbuddy~buildbuddy_toolchain//:platform_linux_arm64; it has already selected a toolchain
      ToolchainResolution:     Incompatible execution platform @@toolchains_buildbuddy~~buildbuddy~buildbuddy_toolchain//:platform_linux_x86_64; mismatching values: aarch64
      ToolchainResolution:     Incompatible execution platform @@toolchains_buildbuddy~~buildbuddy~buildbuddy_toolchain//:platform_windows; mismatching values: aarch64, linux
      ToolchainResolution:     Skipping execution platform @@platforms//host:host; it has already selected a toolchain
      ToolchainResolution:   Rejected toolchain @@local_config_cc//:cc-compiler-armeabi-v7a; mismatching values: armv7, android
      ToolchainResolution: Recap of selected @@bazel_tools//tools/cpp:toolchain_type toolchains for target platform @@toolchains_buildbuddy~~buildbuddy~buildbuddy_toolchain//:platform_linux_arm64:
      ToolchainResolution:   Selected @@bazel_tools~cc_configure_extension~local_config_cc//:cc-compiler-aarch64 to run on execution platform @@toolchains_buildbuddy~~buildbuddy~buildbuddy_toolchain//:platform_linux_arm64
      ToolchainResolution:   Selected @@bazel_tools~cc_configure_extension~local_config_cc//:cc-compiler-aarch64 to run on execution platform @@platforms//host:host
INFO: ToolchainResolution: Target platform @@toolchains_buildbuddy~~buildbuddy~buildbuddy_toolchain//:platform_linux_arm64: Selected execution platform @@toolchains_buildbuddy~~buildbuddy~buildbuddy_toolchain//:platform_linux_arm64, type @@bazel_tools//tools/cpp:toolchain_type -> toolchain @@bazel_tools~cc_configure_extension~local_config_cc//:cc-compiler-aarch64
INFO: ToolchainResolution: Target platform @@toolchains_buildbuddy~~buildbuddy~buildbuddy_toolchain//:platform_linux_arm64: Selected execution platform @@toolchains_buildbuddy~~buildbuddy~buildbuddy_toolchain//:platform_linux_arm64, type @@bazel_tools//tools/cpp:toolchain_type -> toolchain @@bazel_tools~cc_configure_extension~local_config_cc//:cc-compiler-aarch64
INFO: ToolchainResolution: Performing resolution of @@bazel_tools//tools/cpp:toolchain_type for target platform @@toolchains_buildbuddy~~buildbuddy~buildbuddy_toolchain//:platform_darwin_arm64
      ToolchainResolution:   Rejected toolchain @@toolchains_buildbuddy~~buildbuddy~buildbuddy_toolchain//:ubuntu_local_cc_toolchain; mismatching values: x86_64, linux
      ToolchainResolution:   Rejected toolchain @@toolchains_buildbuddy~~buildbuddy~buildbuddy_toolchain//:ubuntu_local_cc_toolchain; mismatching values: x86_64, linux
      ToolchainResolution:   Rejected toolchain @@toolchains_buildbuddy~~buildbuddy~buildbuddy_toolchain//:msvc_toolchain; mismatching values: x86_64, windows
      ToolchainResolution:   Rejected toolchain @@bazel_tools~cc_configure_extension~local_config_cc//:cc-compiler-aarch64; mismatching values: linux
      ToolchainResolution:   Rejected toolchain @@bazel_tools~cc_configure_extension~local_config_cc//:cc-compiler-armeabi-v7a; mismatching values: armv7, android
      ToolchainResolution:   Rejected toolchain @@rules_cc~~cc_configure_extension~local_config_cc//:cc-compiler-aarch64; mismatching values: linux
      ToolchainResolution:   Rejected toolchain @@rules_cc~~cc_configure_extension~local_config_cc//:cc-compiler-armeabi-v7a; mismatching values: armv7, android
      ToolchainResolution:   Rejected toolchain @@local_config_cc//:cc-compiler-aarch64; mismatching values: linux
      ToolchainResolution:   Rejected toolchain @@local_config_cc//:cc-compiler-armeabi-v7a; mismatching values: armv7, android
      ToolchainResolution: No @@bazel_tools//tools/cpp:toolchain_type toolchain found for target platform @@toolchains_buildbuddy~~buildbuddy~buildbuddy_toolchain//:platform_darwin_arm64.
ERROR: /home/peterkolloch/.cache/bazel/_bazel_peterkolloch/824dcaf761632cbc9a32ed7cf6ce3b6a/external/rules_rust~~crate~crates__backtrace-0.3.71/BUILD.bazel:87:19: While resolving toolchains for target @@rules_rust~~crate~crates__backtrace-0.3.71//:_bs_ (d995082): No matching toolchains found for types @@bazel_tools//tools/cpp:toolchain_type.
To debug, rerun with --toolchain_resolution_debug='@@bazel_tools//tools/cpp:toolchain_type'
If platforms or toolchains are a new concept for you, we'd encourage reading https://bazel.build/concepts/platforms-intro.
ERROR: /home/peterkolloch/.cache/bazel/_bazel_peterkolloch/824dcaf761632cbc9a32ed7cf6ce3b6a/external/rules_rust~~crate~crates__libc-0.2.167/BUILD.bazel:65:19: While resolving toolchains for target @@rules_rust~~crate~crates__libc-0.2.167//:_bs_ (d995082): No matching toolchains found for types @@bazel_tools//tools/cpp:toolchain_type.
To debug, rerun with --toolchain_resolution_debug='@@bazel_tools//tools/cpp:toolchain_type'
If platforms or toolchains are a new concept for you, we'd encourage reading https://bazel.build/concepts/platforms-intro.
ERROR: /home/peterkolloch/.cache/bazel/_bazel_peterkolloch/824dcaf761632cbc9a32ed7cf6ce3b6a/external/rules_rust~~crate~crates__eyre-0.6.12/BUILD.bazel:67:19: While resolving toolchains for target @@rules_rust~~crate~crates__eyre-0.6.12//:_bs_ (d995082): No matching toolchains found for types @@bazel_tools//tools/cpp:toolchain_type.
To debug, rerun with --toolchain_resolution_debug='@@bazel_tools//tools/cpp:toolchain_type'
If platforms or toolchains are a new concept for you, we'd encourage reading https://bazel.build/concepts/platforms-intro.
ERROR: /home/peterkolloch/.cache/bazel/_bazel_peterkolloch/824dcaf761632cbc9a32ed7cf6ce3b6a/external/rules_rust~/cargo/private/BUILD.bazel:4:12: While resolving toolchains for target @@rules_rust~//cargo/private:copy_file (d995082): No matching toolchains found for types @@bazel_tools//tools/cpp:toolchain_type.
To debug, rerun with --toolchain_resolution_debug='@@bazel_tools//tools/cpp:toolchain_type'
If platforms or toolchains are a new concept for you, we'd encourage reading https://bazel.build/concepts/platforms-intro.
ERROR: /home/peterkolloch/.cache/bazel/_bazel_peterkolloch/824dcaf761632cbc9a32ed7cf6ce3b6a/external/rules_rust~~crate~crates__proc-macro2-1.0.92/BUILD.bazel:66:19: While resolving toolchains for target @@rules_rust~~crate~crates__proc-macro2-1.0.92//:_bs_ (d995082): No matching toolchains found for types @@bazel_tools//tools/cpp:toolchain_type.
To debug, rerun with --toolchain_resolution_debug='@@bazel_tools//tools/cpp:toolchain_type'
If platforms or toolchains are a new concept for you, we'd encourage reading https://bazel.build/concepts/platforms-intro.
WARNING: errors encountered while analyzing target '//crates/hello_world:hello_world', it will not be built.
Analysis failed
INFO: Analyzed target //crates/hello_world:hello_world (204 packages loaded, 6261 targets configured).
WARNING: errors encountered while analyzing target '//crates/hello_world:hello_world', it will not be built.
Analysis failed
INFO: Found 0 targets...
ERROR: command succeeded, but not all targets were analyzed
INFO: Elapsed time: 3.107s, Critical Path: 0.00s
INFO: 1 process: 1 internal.
ERROR: Build did NOT complete successfully
```

It seems to work both in CI (with `--config remote`) and on Mac OS ARM, though.

**Comment by sluongng** [comment] 2024-12-04 14:07
We just merged https://github.com/buildbuddy-io/buildbuddy-toolchain/commit/96323fd34cc72aacaad28d0e60489f64521c9eb6 which I think should fix this. Could you please update and let me know if the issue is gone?

**Comment by kolloch** [comment] 2024-12-04 15:43
@sluongng Yes, it does work on Mac OS ARM (without enabling the toolchain), on Linux ARM (in a VM without enabling the toolchain) and in CI Linux x86 (with buildbuddy toolchain).

🙏 👍

**Comment by sluongng** [comment] 2024-12-04 16:30
Thanks for testing it out. It's great to get this early report before we get this module into BCR 😅

**Closed by sluongng** 2024-12-04 16:30 UTC

**Comment by kolloch** [comment] 2024-12-05 18:54
Thank you for reacting so quickly and fixing my issue :)
